### ISSUE TITLE
Screen: Time tracking data entry

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#101]
There are three ways of entering time tracking data:
1. uploading a spreadsheet (
2. uploading a calendar file (.ics)
3. querying the data from a cloud calendar

Design the UX/UI for this and add to a screen.

Display the result, i.e. the time tracking data (e.g. via DataTable).

Preferences management:
- Selecting the preferred method of time tracking
- managing credentials for the cloud calendar

**Comment by clstaudt** [comment]
@vlad-ed-git   The screen for getting the time tracking data from the cloud calendar may be a s simple as having a reload button (🔄)  and possibly a field or dropdown menu to set the calendar name.

**Comment by vlad-ed-git** [comment]
@clstaudt If I understand correctly, we have two instances. 

1. The user has not set any iCloud account in their preferences.  In which case they would provide the name of account, a password and this would configure that account. After this.
2. They set a calendar name and click a button to load the data from this calendar name. Calendar names that have already been added can be accessed from a drop down list to be selected for reload. 

Is this correct?

**Comment by clstaudt** [comment]
@vlad-ed-git 

Re 1.: we can require that the account is configured in the preferences. The option to configure it "just in time" is not needed for the MVP. If it's not configured the option to get the time tracking data from the cloud is not available.

Re 2:  For the first iteration a text field to set the name will do. Nice to have: There's probably a way to list all available calendars for the cloud account. In that case login would have to come before calendar selection.

**Comment by clstaudt** [comment]
Basically what the screen should do is calling `timetracking.import_from_calendar` and display the resulting DataFrame:

```python
def import_from_calendar(cal: Calendar) -> DataFrame
```

The calendar may be a `FileCalendar` that was just uploaded or a `CloudCalendar` that can be queried.

To simplify you may ignore the spreadsheet upload option for now.

**Comment by vlad-ed-git** [comment]
@clstaudt please check the latest implementation if the setup is correct. 
**there is some sort of glitch now with dialogs, I need to check the refactoring you have done on `app.py` for this.

**Comment by vlad-ed-git** [comment]
I am referring to the flow on the UI. Calendar access is backend
integration. I mean is the flow correct or do you wish to change it?
By flow I mean:
 User clicks new, they see 3 options, one of them is to use iCloud acc (can
be renamed to a more generic name, that's fine),  they click on that and
provide a calendar name and password (this acc is saved or pulled from the
preferences setup). Or does configuration require more information?

**Comment by clstaudt** [comment]
@vlad-ed-git  There's an additional step for the cloud access we have to consider. Have a look at `tuttle.cloud.login_iCloud`. It usually asks for a 2FA code that is displayed on your Mac or iPhone. In the UI there needs to be a popup that requests this code.

**Comment by clstaudt** [comment]
There is also an UI bug when trying to access the cloud calendar:



![Image](https://user-images.githubusercontent.com/875194/211802014-f42c3456-b066-42f5-8ae8-8488b97b72b6.png)

**Comment by clstaudt** [comment]
@vlad-ed-git   I have trouble moving forward here because it seems entirely broken from the UI side: For example, when I try to upload an .ics file I get "new progress is being recorded" and then the app reloads. No error message displayed or logged. Error hiding? 👎👎👎

**Comment by vlad-ed-git** [comment]
*The app reloads if you run the app using flet ... -r -d, which listens to
all changes in all directories. Since you just upload a file to the uploads
directory , this command intepretes it as a change in the app and reloads
the app. Instead run the app without those flags .

*The intent shall pass to you the path to this ics file for processing (I
think I have that in place already) . Same for spreadsheet.

**Comment by clstaudt** [comment]
Yes I just noticed that. That's annoying, why does the reload option monitor the upload folder...

**Comment by clstaudt** [comment]
@vlad-ed-git 

```
class TimeTrackingDataSource(SQLModelDataSourceMixin):
    def __init__(self):
        super().__init__()

    def process_timetracking_file(self, file_name) -> IntentResult:
        """process a recently uploaded time tracking file in .xlsx or .ics format
        returns was_intent_successful = True if processing completed successfully
        else was_intent_successful = False and err_msg are set
        """
        return IntentResult(was_intent_successful=True, data=None)
```

This codes hides the fact that processing the file is not yet implemented. What would be a better way to show that the intent is yet to be implemented?

**Comment by clstaudt** [comment]
@vlad-ed-git  My tendency here is to go back to the drawing board together and trying to rewrite this screen.

**Comment by vlad-ed-git** [comment]
Just have process_timetracking_file return intent successful as False with
an Unimplemented error message.

**Comment by vlad-ed-git** [comment]
@clstaudt uploading a calendar file (.ics) now works. Please review. *Flet's data table control does not work for some reason (DataTable) cannot be imported. So I created a bare bones tabular structure instead.

**Comment by vlad-ed-git** [comment]
@clstaudt I found the issue with not being able to import DataTable , I was using an earlier version of flet. Upgraded and now I can call the `data_frame_to_data_table` method you created.

**Comment by clstaudt** [comment]
@vlad-ed-git great, that was a weird error because I already tested DataTable

**Comment by vlad-ed-git** [comment]
After upgrading, pip is telling me this:
>
> ERROR: pip's dependency resolver does not currently take into account all
> the packages that are installed. This behaviour is the source of the
> following dependency conflicts.
> tuttle 0.2.1 requires flet<0.2.0,>=0.1.65, but you have flet 0.3.2 which
> is incompatible.


The app works though. I can't find where this specification
*flet<0.2.0,>=0.1.65*, is set.

**Comment by clstaudt** [comment]
Will investigate

**Comment by clstaudt** [comment]
@vlad-ed-git   When doing a clean install, I can't  reproduce your dependency error. When in doubt clone a new copy of the repo. If you still encounter a problem create a new ticket please.

**Comment by vlad-ed-git** [comment]
@clstaudt clean install worked. I also needed to remove conda as it was not playing well with my homebrew's python.
