### ISSUE TITLE
Function: Upload and display user profile photo

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#104]
The user should be able to customize the app by adding their profile picture or logo to the profile page.

**Comment by clstaudt** [comment]
@vlad-ed-git  This does not yet work properly

**Comment by vlad-ed-git** [comment]
@clstaudt Fixed now (but pending backend implementation of `update_user_photo_url` and `update_user`)

**Comment by vlad-ed-git** [comment]
@clstaudt also to allow the client to read upload files, they should be saved in a location within assets. See the specified `upload_dir` in the app.py file (very last line). If you wish to store uploaded files in another location, like the .tuttle one, I think we might have to use read file operations in python, then convert the photo to something like a base64 string and then pass it back to the client side (UI) for display.

**Comment by clstaudt** [comment]
Why the base64 encoding step? Doesn't flet support images from files? 
https://github.com/flet-dev/flet/issues/651

**Comment by vlad-ed-git** [comment]
@clstaudt Images have two ways to setup. With src (but this expects a path to be within the assets folder). OR base64. There is also a url option but that expects a web url.

**Comment by clstaudt** [comment]
okay.


```python
import base64

def image_to_base64(image_path):
    with open(image_path, "rb") as image_file:
        encoded_string = base64.b64encode(image_file.read()).decode('utf-8')
    return encoded_string
```

**Comment by vlad-ed-git** [comment]
ok will try this
