### ISSUE TITLE
Preferences: organize into tabs & groups

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#105]
Design an extensible UI for managing different groups of settings in the Preferences screen.

**Comment by clstaudt** [comment]
Possible groups:

- ☁️ Cloud: Manage cloud connector settings (e.g. calendar name for time tracking and time planning) and credentials
- 🗺️ Locale: Manage things like language, country (e.g. for taxation), default currency...

**Comment by clstaudt** [comment]
UI style: macOS-like, tabs with icons and text

![Image](https://user-images.githubusercontent.com/875194/211306205-70ea1024-d2f3-48ea-a8f5-0113fc53fa3f.png)

**Comment by clstaudt** [comment]
@vlad-ed-git   I have tried twice to add flet.Tabs (https://flet.dev/docs/controls/tabs/) to the Preferences screen. This didn't work and messed up the layout entirely. Could you add a minimal working example for organizing the preferences into tabs?

For example:
- tab "General" ⚙️: light/dark theme switch
- tab "Cloud" ☁️: iCloud account name

**Comment by vlad-ed-git** [comment]
@clstaudt I tried (see my latest commit), but I don't think it looks good (and I don't see how we can get it to look as the screenshot you posted).

**Comment by clstaudt** [comment]
Screenshot please, I don't see any tabs here:

![Screenshot 2023-01-10 at 10 37 08](https://user-images.githubusercontent.com/875194/211515401-8719f1bf-ddb2-4927-b83b-56c8c135b10f.png)
