### ISSUE TITLE
Preferences: Cloud credentials management

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#106]
The Preferences screen should contain a section for managing cloud credentials - for now iCloud, in the future Google Cloud etc.

**Comment by clstaudt** [comment]
@vlad-ed-git  please test and review

**Comment by vlad-ed-git** [comment]
@clstaudt wouldn't it be best to offer two fields (or more), one for each provider so that the user has an option to have 2 or more accounts. For example, I tend to use both the iCloud and google calendars.

**Comment by clstaudt** [comment]
Not for the MVP. People usually have one.

**Comment by vlad-ed-git** [comment]
okay.
