### ISSUE TITLE
View: Invoice

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#108]
After generating invoices, they should be visible and accessible in the app:

- card per invoice?
- PDF document thumbnail?
- cross-platform PDF preview function?
- cross-platform dialog for sending an invoice by email?

**Comment by vlad-ed-git** [comment]
That belongs in core.views. if it will appear in multiple other views.
Otherwise it will be part of invoice.views and imported from there.

**Comment by clstaudt** [comment]
Kind of makes sense to put it in invoice/view.py.  There's no problem with cross-importing from other "screen" modules, right?

**Comment by vlad-ed-git** [comment]
Yes. That's fine. It only goes in core views if it really is a core
component (e.g. a generic drop-down )

**Comment by vlad-ed-git** [comment]
@clstaudt the data sources for this are pending implementation. The Ui is ready for review.
