### ISSUE TITLE
demo data mode

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#110]
Switch (e.g. flag for the app command) that activates demo mode, in which the app is populated with fake data.

**Comment by clstaudt** [comment]
@vlad-ed-git 

How can we pass an option `demo_mode` to the app run command so that if `demo_mode == True` fake data is installed?

```python

def main(page: Page):
    """Entry point of the app"""
    app = TuttleApp(page)

    # install demo data
    try:
        app_dir = ensure_app_dir()
        demo.install_demo_data(
            n=10,
            db_path=app_dir / "tuttle.db",
        )
    except Exception as ex:
        logger.exception(ex)
        logger.error("Failed to install demo data")
    app.build()


if __name__ == "__main__":
    flet.app(
        name="Tuttle",
        target=main,
        assets_dir="assets",
        upload_dir=ensure_app_dir() / "uploads",
    )
```

**Comment by vlad-ed-git** [comment]
@clstaudt we can add this option on the login screen. Where we had the skip button, instead of that, we can have a use `preview with demo data` option. We will need then to offer a way within the app to get off this mode (essentially delete all data and restart).

**Comment by clstaudt** [comment]
Good idea, but for now I just want an option that I can pass to the run command.

**Comment by clstaudt** [comment]
https://github.com/flet-dev/flet/discussions/856

**Comment by clstaudt** [comment]
@vlad-ed-git   Quickly: Where in the code should I place a button that appears on the splash screen below the registration form and says "Install demo data"?

**Comment by vlad-ed-git** [comment]
@clstaudt in `SplashScreen.build`, there is a  `page_view` with `ResponsiveRow` that has two containers . the last container has it's `content=self.form_container`. Change this to a content to a container to a column, with the column controls set to [self.form_container, self.YOUR_DEMO_BTN_CONTROL] to place the button below the form
