### ISSUE TITLE
Installing demo data runs indefinitely

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#114]
When running app, trying to install demo data goes into an infinite loop with a log message `installing demo data`. 
Device : Mac OS 13.1 (Ventura), M1 chip. 
To recreate: Run `flet app/app.py -d -r` from within the tuttle directory.

**Comment by clstaudt** [comment]
@vlad-ed-git  I think is not an issue with the code but the auto-reload feature (the -r flag?). As soon as the database file gets written in the app/tmp folder, flet tries to reload everything, resulting in the infinite loop.

`flet app/app.py` works.

I guess to avoid the issue with autoreload the database should be created in user space and not the app folder.

**Comment by clstaudt** [comment]
@vlad-ed-git fixed, should work with autoreload - please test and close
