### ISSUE TITLE
Architecture: Forms & model

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#122]
The code in `auth.view` strikes me as very verbose. 

A class like `LoginForm` is 250 lines of code, just for editing and validating data for a single model object. `LoginForm` and `User` are tightly coupled, so there is a lot of redundancy here. A change of the `User` class possibly triggers a bunch of work in the `LoginForm` class. 

Whenever I see so much code for a relatively simple thing, I think that we are missing the right technology. Isn't there a better approach for getting the data for the  `User` model from a form? Some library that maps models to forms and vice-versa? Or at least a way to automatically generate the code for the form, rather than writing it by hand?

**Comment by vlad-ed-git** [comment]
@clstaudt without a specific section of the code, I can't really answer this.

**Comment by clstaudt** [comment]
@vlad-ed-git   The file `app/auth/view.py` has 700 lines. 700. That's my complaint. Maybe it has to be this way but I would triple-check because the app will have numerous forms and I don't want 80% of the code base to be form handling.

**Comment by clstaudt** [comment]
Possibly relevant: https://wtforms.readthedocs.io

**Comment by vlad-ed-git** [comment]
@clstaudt got this down from 700 to 480 😄

**Comment by clstaudt** [comment]
@vlad-ed-git Thanks. UI code is still quite verbose and requires a lot of boilerplate code, but perhaps flet leaves no other option. Let's run with it for the MVP. My hope is that it becomes manageable with ChatGPT.
