### ISSUE TITLE
Item deletion

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#125]
So far data items (Projects, Contacts...) cannot be deleted.

**Comment by clstaudt** [comment]
@vlad-ed-git  Please add UI elements and methods to delete items. Methods can be stubs, you can leave backend integration to me.

**Comment by vlad-ed-git** [comment]
on it

**Comment by vlad-ed-git** [comment]
@clstaudt `Project deletion` completed on UI side. please review and implement data source method

**Comment by vlad-ed-git** [comment]
@clstaudt `Client deletion` completed on Ui side. please review and implement the data source method

**Comment by vlad-ed-git** [comment]
@clstaudt Passing the entity is fine too I suppose. I can pass that if that's preferred

**Comment by clstaudt** [comment]
My gut feeling says whenever possible handle entity objects, not ids.

**Comment by clstaudt** [comment]
![Screenshot 2023-01-12 at 11 59 58](https://user-images.githubusercontent.com/875194/212049588-02cd6afe-7bde-48ea-9388-efc0d7ad7c31.png)

What do you think of my design: Card with a ListTile header, which also contains the contextual menu. Should this be applied to all the entity cards?

**Comment by vlad-ed-git** [comment]
There is actually a riskier element with passing around objects (for deletion or updating) because they are actually passed as references. More bugs to think of in that scenario. 

On another note, something to think of, should a project deletion (on the data source) also delete the associated contract (or the vice versa)? Aren't these two directly mapped?

**Comment by vlad-ed-git** [comment]
on the design you propose, @clstaudt project, contracts and client titles and their descriptions might not fit so neatly in that section the way a contact name _probably_ always will .  We would have to truncate the text and add ellipsis or something, which may or may not look weird.

**Comment by clstaudt** [comment]
> On another note, something to think of, should a project deletion (on the data source) also delete the associated contract (or the vice versa)? Aren't these two directly mapped?

I don't think so. What would be the problem with deleting a project but keeping the contract?

> There is actually a riskier element with passing around objects (for deletion or updating) because they are actually passed as references. More bugs to think of in that scenario.

Currently I find it hard to imagine the pros and cons. Need to build more stuff.


> project, contracts and client titles and their descriptions might not fit so neatly in that section the way a contact name probably always will

If it's long text (description), don't display it in the ListTile but the Card area below. Require project titles to be short.

**Comment by vlad-ed-git** [comment]
@clstaudt `Contract deletion` completed on ui side. Please review and  implement the data source

**Comment by vlad-ed-git** [comment]
@clstaudt `If it's long text (description), don't display it in the ListTile but the Card area below. Require project titles to be short.`  Lets move this to a new issue .
