### ISSUE TITLE
migrate useful UI features from demo app

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#126]

**Comment by clstaudt** [comment]
@vlad-ed-git   Please review the demo app 

```shell
>python app_demo/Tuttle.py
```

- to see which UI ideas should be brought into the main app
- to see rudimentary implementations of the time tracking & invoicing workflows

**Comment by clstaudt** [comment]
I think popup menus (`PopupMenuButton` etc) are a good idea. 

![Image](https://user-images.githubusercontent.com/875194/211686092-a21e12b5-156d-4a6d-8e38-70550fe29bc0.png)

**Comment by clstaudt** [comment]
@vlad-ed-git  How about grouping the edit, delete, show details etc. buttons with a PopupMenuButton?

**Comment by vlad-ed-git** [comment]
I am thinking the same
