### ISSUE TITLE
Code style refactoring

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#131]
A) 

```python
import flet

flet.Text(....)
```

B)

```python
from flet import (
    Text,
)
```

**Comment by clstaudt** [comment]
Which style do you prefer?

In any case, pick one and keep it consistent throughout the project.

Don't do this, it's silly:

```
import flet as ft
```

I know the flet developers do it but I think it's a silly trend, saving two letters and risking even more package name collisions than we already have in the Python world.

**Comment by clstaudt** [comment]
Let's go for style B then.

It's not just about the amount of lines, it's about understandable code. 

My thinking: When I am writing a UI view, then the components from flet are "first class citizens", I import them directly. It's clear where these things come from when I write a flet app. Other things that I need I tend to import indirectly because it's not immediately clear where they are from.

**Comment by vlad-ed-git** [comment]
Style B is import Flet and use flet.control?

**Comment by clstaudt** [comment]
```python
from flet import (
    Text,
    UserControl,
    ElevatedButton,
)

a_button = ElevatedButton()
```

**Comment by vlad-ed-git** [comment]
Okay

**Comment by vlad-ed-git** [comment]
TODOs 

1. refactor to use consistent flet imports
2. refactor to have necessary doc strings
