### ISSUE TITLE
Ui Design Fixes

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#135]
- [x] - Can we decrease the font size so that it matches the font size of native apps on the different platforms? suggested by @clstaudt 

- [x] - Use ListTile on Cards

- [x] - Refactor imports

- [x] - Design: native-style background color for side bar, top bar, footer

- [x] -  Fix the gap in the border

**Comment by vlad-ed-git** [comment]
@clstaudt I have moved the ui todos here.

**Comment by clstaudt** [comment]
<img width="345" alt="Screenshot 2023-01-19 at 10 38 36" src="https://user-images.githubusercontent.com/875194/213407893-683ff867-1f9a-4bf7-a947-12e918e8d7eb.png">

Tweak area borders to look more native. Fix the gap in the border
