### ISSUE TITLE
Dialog: New Invoice

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#136]

**Comment by clstaudt** [comment]
@vlad-ed-git please note: the invoice number is automatically generated according to a schema that the user can select. So a free text field to enter it shouldn't be there.

**Comment by vlad-ed-git** [comment]
*okay noted. Is this generated during saving (in which case when I pass
Invoice entity to be store it should have no number set  ) or do I call a
generate number method when the user is adding other info (like date)?

**Comment by vlad-ed-git** [comment]
Fixed : Invoice number has been set to uneditable. 
Pending data source implementation.
