### ISSUE TITLE
View: Contract card should display the most relevant attributes in a clean layout

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#142]

**Comment by clstaudt** [comment]
![Image](https://user-images.githubusercontent.com/875194/212570982-5bf78e3e-a353-4153-a375-b9b0aa692f66.png)


@vlad-ed-git  At this point I wouldn't say that the contract card shows you the most important info at a glance

**Comment by vlad-ed-git** [comment]
@clstaudt what are the most important attributes of a contract?

**Comment by vlad-ed-git** [comment]
What is displayed, the contract title, client name, billing cycle, and
start and end date are what I think are important on the quick-view.

**Comment by clstaudt** [comment]
What about the money?!

**Comment by clstaudt** [comment]
Pass me the ticket, I want to learn to layout these cards.

**Comment by vlad-ed-git** [comment]
okat
