### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#145]
Architectural refactoring to a specific standard.

**Comment by vlad-ed-git** [comment]
- [ ] Setting attributes during an update should be moved to Intent class
- [ ] If an update fails, the Intent should return the old entity

**Comment by clstaudt** [comment]
@vlad-ed-git  What is the status of this? Can it be merged into the dev branch before there is much divergence?

**Comment by vlad-ed-git** [comment]
The progress so far is already merged

**Comment by clstaudt** [comment]
#207
