### ISSUE TITLE
On Delete item cascading

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#146]
- [x] Test deleting a contact -> what happens to the client holding it
- [x] Test deleting a client -> what happens with the contract or project referencing it
- [x] Test deleting a contract -> what happens to the project referencing it

**Comment by clstaudt** [comment]
The logic is straightforward: As long as a Contact is required by a Client, then it cannot be deleted. I think it's clear that the user does not want "cascading" deletion.

So, test for `len(contact.invoicing_contact_of) > 0`, if true do not allow deletion.

The implementation in the current MVI architecture is not straightforward though. e.g.: Where should this test happen? In the intent or the data source?

I chose the intent layer and implemented it for the deletion of contacts. @vlad-ed-git  Please review my implementation.

**Comment by vlad-ed-git** [comment]
Preserving the integrity/relationship of the data models in a database is the responsibility of the data layer, so it goes into the data source. Similar to how during insertion the `on conflict` strategy is something handled over the data layer.

**Comment by vlad-ed-git** [comment]
* The above tasks fall under entity integrity management, and should thus be done in the data source.

        *  if you are wondering how the intent would know if a delete did not happen because of some other error or because the object being deleted is depended on by another, this is where _**error_codes**_  typically come in. 
        The IntentResult can define an error code (Error codes might be wrapped in enums for readability). 
        So in the case where a deletion fails because the entity being deleted is being used by another entity, the data source will return IntentResult with was_intent_sucessful = False, log_message="...IntegrityError, attempting to delete an entity referenced by another ...", error_code = ErrorCodes.IntegrityError

**Comment by clstaudt** [comment]
Thanks for clarifying.

- transforms the event data to the data format required by the data source
- transform returned data source data to the data format required by the Ui

Somewhat missing from the picture is the role of an ORM (Object Relational Mapper) library. It seems to me that with SQLModel the data format required by the UI and the data source is often exactly the same. So not much transformation going on in practice.

**Comment by clstaudt** [comment]
https://github.com/tiangolo/sqlmodel/issues/533#issuecomment-1396575491

**Comment by vlad-ed-git** [comment]
@clstaudt To clarify this, "Somewhat missing from the picture is the role of an ORM (Object Relational Mapper)." 

The abstraction that the ORM is doing is not specific to the models of project Tuttle. 
It's hence not a replacement for the data source of Tuttle. 

In the same way that flet (which abstracts the implementation of a button) is not a replacement for the View layer of Tuttle.
Tuttle's views are aware of how the update profile button looks and what events it listens for, similarly, the data source layer is aware of what updating a user profile entails for a given User model.

On the other hand, flet defines how a generic button looks and what events that button can listen to, and the ORM defines how a generic model can be stored in a table and how updating such a model is done.
