### ISSUE TITLE
UI: Invoices should not be editable

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#148]
Invoices are treated immutable. Rather than implementing a complex editing logic, tell the user to cancel or delete and recreate the invoice if it isn't correct.

**Comment by clstaudt** [comment]
That also means that view_edit_delete_popup isn't as reusable as planned. Give every data item a completely customizable popup menu instead.

**Comment by vlad-ed-git** [comment]
This is solvable by just removing making edit optional in the view_edit_delete_popup and removing the edit choice on invoice. The view_edit_delete_popup is re used in each model except timetracking, and customization is done via parameters.
