### ISSUE TITLE
Bug: Cannot select Project for invoicing

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#149]
Had a situation where a Project cannot be selected for invoicing even though one exists.

No error message logged or displayed (error hiding?).

![Image](https://user-images.githubusercontent.com/875194/213315337-8295d25c-e810-4dd1-b07d-04a7b5fb45f9.png)

![Image](https://user-images.githubusercontent.com/875194/213315346-5548f5db-d53e-4284-b8dd-27b6b28afa8d.png)

**Comment by vlad-ed-git** [comment]
fixed on [commit](https://github.com/tuttle-dev/tuttle/commit/428f540af5c610888d763258fad20243b5fae7a9)
