### ISSUE TITLE
Bug: OSError: cannot load library 'gobject-2.0-0'

### ISSUE THREAD

**Issue by tweakimp** [tuttle-dev/tuttle#156]
```
=== short test summary info ===
FAILED tuttle_tests/test_invoice.py::test_render_invoice_to_pdf
 - OSError: cannot load library 'gobject-2.0-0': error 0x7e. 
Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
=== 1 failed, 14 passed, 20 warnings in 7.48s ===
```

Steps to reproduce:
1. Be on Windows 10, use Python 3.10.
2. Create virtual environment `python -m venv env`
3. Activate it with `.\env\Scripts\activate`
4. Install requirements with `pip install -e . `
5. Run pytest `pytest`

**Comment by clstaudt** [comment]
@tweakimp  It seems that running on Windows requires GTK to be installed before in a separate step. 

- Do you still get the error if you follow this: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows
- Were you able to start and run the app?
- In the app demo, were invoices rendered as PDF? (Invoice context menu -> View)

**Comment by clstaudt** [comment]
@tweakimp  Could you also please check if there is a solution here? https://stackoverflow.com/questions/63449770/oserror-cannot-load-library-gobject-2-0-error-0x7e
