### ISSUE TITLE
Bug: Generated invoice total hours are incorrect

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#164]
The total hours on a generated invoice exceed that of the time tracking dataframe

**Comment by clstaudt** [comment]
@vlad-ed-git  ... in some cases. Working on narrowing down the error case.

**Comment by clstaudt** [comment]
@vlad-ed-git  Is the total correct for you if you do not enter whole-day events into the calendar?

**Comment by vlad-ed-git** [comment]
@clstaudt no. still having this issue. If I delete an invoice and create a new one. it seems to add the information from the previous one! 

[2023-01-23-01-dr.rer.nat..pdf](https://github.com/tuttle-dev/tuttle/files/10476979/2023-01-23-01-dr.rer.nat.pdf)

**Comment by clstaudt** [comment]
@vlad-ed-git  Can you send me the calendar file? Will try and debug.

**Comment by vlad-ed-git** [comment]
@clstaudt I don't know if you still need the file, but I emailed it to you.

**Comment by clstaudt** [comment]
@vlad-ed-git  Thanks. I think it's an issue with the SQLModel integrity, not with your data, but test data always helps.

**Comment by clstaudt** [comment]
@vlad-ed-git  This should be fixed in the `dev` branch now if you want to try again.
