### ISSUE TITLE
UI: User registration: make phone number optional

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#167]

**Comment by flamesjames** [comment]
Hey there @clstaudt! Does this issue still need worked on? If so, I would be glad to help out with it.

**Comment by clstaudt** [comment]
Hi @flamesjames, thanks for asking. I think we're just about to close this, but there is no shortage of similar tasks. What would you like to work on in general?

**Comment by flamesjames** [comment]
That would be fantastic! Let me know which ones you'd like me take a look at

**Comment by clstaudt** [comment]
@flamesjames Please accept my invite to the project so I can mention you in suitable issues.

**Comment by flamesjames** [comment]
Thanks a lot! I just accepted.
