### ISSUE TITLE
Bug: Contact form validation

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#170]
Tester:

> When I did not put a first name for a contact, upon clicking done the modal simply closed, with a error message in the main window that I did not notice immediately. I then had to start filling out the contact info from scratch.

**Comment by krasch** [comment]
Tester here: I believe that this might be the same with other modals, too

**Comment by vlad-ed-git** [comment]
@clstaudt fixed on dev-refactoring branch. Pending merge to dev and review
