### ISSUE TITLE
UI: registration / user profile: ask user for website

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#182]
```python
    website: Optional[str] = Field(
        default=None,
        description="URL of the user's website.",
    )
```

This is an attribute of the `User` model that is not in the registration / user profile form.

**Comment by clstaudt** [comment]
@vlad-ed-git  Now it's there, thanks. But revealing another issue: The forms are so long that the window content is scrolling. At least on my Macbook Air it doesn't fit into a fullscreen window anymore.  


![Image](https://user-images.githubusercontent.com/875194/214140126-7ba127ab-675c-415c-80fb-9dedf58c9463.png)


![Image](https://user-images.githubusercontent.com/875194/214140057-78b30097-2aa3-41b6-8501-184809f776c9.png)

**Comment by vlad-ed-git** [comment]
@clstaudt please review latest update.

**Comment by clstaudt** [comment]
👍 for the new tabbed settings design

![Image](https://user-images.githubusercontent.com/875194/214242129-84242e5d-475d-444b-9a4b-a072d2066683.png)
