### ISSUE TITLE
UI bug: Invoice "not rendered" even though PDF exists

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#183]
![Image](https://user-images.githubusercontent.com/875194/214106802-5efc4488-792a-4f43-a0e2-1ab7f2e87382.png)

To reproduce:

1. create a new invoice
2. click "View" to preview the PDF 

this works ✅

3. reload the invoicing screen
4. click "View" on the same invoice

❌ this fails with "invoice has not been rendered" message in the snack bar

**Comment by clstaudt** [comment]
@vlad-ed-git  Please have a look. If it's a backend issue pass the ticket to me.

**Comment by vlad-ed-git** [comment]
@clstaudt It's a backend issue. And I think I know what it is. We save the invoice, render it, update it's rendered property, and never save it again. Perhaps we should render it and then save?

see `create_invoice` intent (under Invoicing).  The call `self._invoicing_data_source.save_invoice(invoice)` is done before rendering the invoice. I think this would cause this bug.

**Comment by vlad-ed-git** [comment]
@clstaudt I moved the save line to after rendering. And I am not getting any errors now.

**Comment by clstaudt** [comment]
@vlad-ed-git  good catch, it's working
