### ISSUE TITLE
UX/UI: Meaning of "Active" filter

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#184]
What is the meaning of the "Active" filter for on the Projects screen? Apparently a project can be both "completed" and "active".

![Image](https://user-images.githubusercontent.com/875194/214114145-65481977-bb83-4e66-a82a-a199fa2a6c6a.png)

**Comment by vlad-ed-git** [comment]
- [ ] fix is_active implementation on both Project and Contract models
- [ ] add tool tip to the filters
