### ISSUE TITLE
UI: Reset button to revert app state to initial settings

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#191]
A reset button should allow the user to revert the app to its default state. The app should then quit.

**Comment by clstaudt** [comment]
I tried the following implementation:

- add reset button to the Preferences screen under General Preferences (`preferences/view.py`)
- add an intent `PreferencesIntent.reset_app`
- a flet app [can only close programmatically](https://github.com/flet-dev/flet/issues/229) by calling `Page.window_close`
- `PreferencesIntent` needs the `Page` every time it is instantiated (?)

@vlad-ed-git  How did you solve the problem of passing the `Page` throughout the app's design? How should it be handled hereß

**Comment by vlad-ed-git** [comment]
I don't pass the page. Just callbacks passed on to screens that are handled by app.

**Comment by clstaudt** [comment]
@vlad-ed-git  Then how would you call  `Page.window_close` on the click of a button on the Preferences screen?

**Comment by vlad-ed-git** [comment]
I would pass a close_window callback to Preferences screen , and have an app method to close the window.

**Comment by clstaudt** [comment]
And how would the app's method get to the many places where a `PreferencesIntent` is instantiated?
<img width="769" alt="Screenshot 2023-01-25 at 22 11 02" src="https://user-images.githubusercontent.com/875194/214691821-99de7d0b-d57f-4ddb-b8ac-337c72d18e62.png">

**Comment by vlad-ed-git** [comment]
I pass these callbacks to the views (see routing section in the app.py file), not to the intent. The view can call close window , it does not need an intent for that.

**Comment by vlad-ed-git** [comment]
* Have the preferences intent handle resetting (deleting all data , etc ) . The view will get the result, and then close the window via the callback.

**Comment by clstaudt** [comment]
@vlad-ed-git So like this?
- the view calls `app.close` via a callback
- the intent calls `app.clear_database` via a callback

**Comment by vlad-ed-git** [comment]
If clearing is done by calling clear database, then both app.clear_database and app.close are done from the view. Just merge them into one callback method.

**Comment by vlad-ed-git** [comment]
something like on_reset_app . This can then clear database, and close the window.

**Comment by clstaudt** [comment]
> If clearing is done by calling clear database, then both app.clear_database and app.close are done from the view. Just merge them into one callback method.

Okay, but clearing the DB is intuitively a data source concern. Resetting the app I would consider an intent, that may need data source error handling. Isn't this inconsistent with the MVI pattern? 🤔

**Comment by vlad-ed-git** [comment]
Yes it is, but having to access the app to clear the database is the source of the inconsistency.

**Comment by vlad-ed-git** [comment]
Creating the database, and the models, and clearing them shouldn't be in the app's logic. 
See what I am doing with the other kind of storage we have (the one we use for preferences) ClientStorageImpl. 
It is part of the core. Flet's implementation of the client storage requires the page. So I  am **forced** to instantiate the storage _from the app_ and pass the page to it, and then provide access to this client storage object as part of TuttleParams to every screen. But even here, I do not implement the storage in the app.

**Comment by vlad-ed-git** [comment]
@clstaudt please checkout this branch `dev-db-refactor`

**Comment by vlad-ed-git** [comment]
@clstaudt the way `dev-db-refactor` handles the database instantiation, offers more consistency. But it's incomplete, as we now have two issues, a good example of both is in the Auth.ProfileScreen view:

1. The client storage is requested by the intent from the views (which they receive as part of view params). Ideally, the intent should have access to the client storage themselves without needing the view, unfortunately, we cannot achieve this because flet's client storage requires a page. _Unless of course we implement client storage in another way, without using flet's way._ 

2. **more important for us** the views have direct access to the database implementation also (the profile screen for instance has a call to `self.database_storage.install_demo_data()`). I will fix this. But let's proceed with this reset button feature, then I shall refactor it.

**Comment by clstaudt** [comment]
I will do a quick & dirty implementation of the reset button then, because that's a feature needed for testing. A Pull Request is linked.

**Comment by vlad-ed-git** [comment]
Yes. Do that, then I shall refactor. Let me know which branch you are working from. If you have not started, you can do it from dev-db-refactor (it is up to date with dev).

**Comment by clstaudt** [comment]
I have started, the draft PR is attached to the ticket (by the way, we should do that always). Will check your branch later @vlad-ed-git

**Comment by clstaudt** [comment]
@vlad-ed-git  I feel that the reset button is working fine for now with the quick&dirty implementation. Would you still like to make changes? If not please close the ticket.

**Comment by vlad-ed-git** [comment]
@clstaudt I added a confirmation dialog, as this is a `dangerous` action. I have no further changes so I will close this.
