### ISSUE TITLE
UI Bug: Payment settings invisible after error on Invoicing screen

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#193]
The Payment settings form can disappear from the Preferences screen.

Steps to reproduce:

1. Check that payment settings form is there

![Image](https://user-images.githubusercontent.com/875194/214674063-d4cd8c8c-eede-494d-9d7f-722baa419ea8.png)

2. Navigate to "Invoicing" screen, receive error message in snack bar

![Image](https://user-images.githubusercontent.com/875194/214674206-0db45441-787f-4ba8-adb4-0521f4ba023a.png)

3.  Check that payment settings form is gone

![Image](https://user-images.githubusercontent.com/875194/214674282-02d2e77e-4b29-42b6-a36f-b41926aa036e.png)

**Comment by clstaudt** [comment]
This looks like an example of the [action at a distance anti-pattern](https://en.wikipedia.org/wiki/Action_at_a_distance_%28computer_programming%29) and may indicate a software architecture problem.

**Comment by vlad-ed-git** [comment]
Ok. Will check.

**Comment by vlad-ed-git** [comment]
fixed on `dev-db-refactor` branch. Pending review and merge to dev.

**Comment by clstaudt** [comment]
Thanks @vlad-ed-git . Was this a minor bug or an architecture problem?

(I'd recommend the following branching policy: One ticket, one branch, one PR.)

**Comment by clstaudt** [comment]
@vlad-ed-git  Could you do the merge please, `dev-db-refactor` currently conflicts with  `dev`.

**Comment by vlad-ed-git** [comment]
>
Was this a minor bug or an architecture problem?

@clstaudt A minor bug.

**Comment by vlad-ed-git** [comment]
@clstaudt I have completed the merge.

**Comment by clstaudt** [comment]
It's working now ✅
