### ISSUE TITLE
UI Bug: only one project selectable for invoicing

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#194]
Steps to reproduce:

1. proceed with demo

2. check that several projects have been created

![Image](https://user-images.githubusercontent.com/875194/214679377-a082ec41-60b6-4b4b-bf0b-d6f5dd61fc55.png)

3. on invoicing screen, try to create new invoice. only one project can be selected

![Image](https://user-images.githubusercontent.com/875194/214679498-8ce1dc01-e805-4761-8db6-383e8b6b1447.png)

**Comment by vlad-ed-git** [comment]
That is weird! Will check what's up.

**Comment by clstaudt** [comment]
@vlad-ed-git   I think that was because only one project was active. My mistake.
