### ISSUE TITLE
UI: Lingering data entry error messages

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#204]
- [ ] Create new project screen:

> I selected a Contract from the dropdown but it was still throwing the “Please specify the contract” validation error message.

- [ ] Contacts screen:

> After adding a Contact on the Contacts screen, the validation displayed in red “You have not added any contacts yet” does not go away. Same thing happened on My Clients screen.

**Comment by vlad-ed-git** [comment]
@clstaudt I believe this bug was prior to me reverting the changes that removed the dropdown item prefixing. Please test with the current dev branch and re-open this ticket if it is still there.
