### ISSUE TITLE
proposal: ask for user data not at startup but at a later point

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#205]
Rough idea: Ask the user to enter data just in time and not upfront.

**Comment by clstaudt** [comment]
@krasch  I wonder, do you still feel like too much data is being asked for upfront?

**Comment by krasch** [comment]
I kind of think that for having a high "conversion rate" (%of people that downloaded the tool that then also gave it a proper effort to try it out) it is helpful to ask as little as possible information upfront. you don't need to know my name even, for most of the functionality of the tool. even for creating an invoice it could be initially seeded with sample address etc and if I am happy with the look of the created invoices I have way more motivation to configure my real data.

but, like I said, I understand that such user flows are hard to implement and maybe it is better to keep things simple for you in the first version, there is so much else that needs to get done, anyway.

also, obviously, I am not an UX expert, just going from my personal experiences navigating user interfaces

**Comment by clstaudt** [comment]
Takeaways for me:
- We should keep the demo data mode for those users who just want to try out
- Perhaps refactor long forms into "assistant"-like multi-step dialogs
