### ISSUE TITLE
Test: Time tracking from Toggl

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#213]
Branch `dev`: Ready for testing with real data:

1. configure projects, contracts, clients
2. import time tracking data recorded with Toggl from .csv file
3. generate invoices and timesheets

**Comment by vlad-ed-git** [comment]
@tsterbak can you try now (get latest dev changes). I suspect it has something to do with the bool | int | None = None type hint.

**Comment by clstaudt** [comment]
@tsterbak @vlad-ed-git   The reason for the error is that this syntax for union types is only available from Python 3.10. 

https://www.blog.pythonlibrary.org/2021/09/11/python-3-10-simplifies-unions-in-type-annotations/

Since we still support Python 3.9 it's a bug and should be changed, even though I prefer the new syntax.
