### ISSUE TITLE
UI: Sidebar layout

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#214]
- [x] The width of the side menu bar currently changes with the window size. Native look&feel requires a fixed width side bar.
- [x] The sub-headings for grouping the menu items are not aligned to the left like in a native app.
- [x] There is a lot of space between the two sub-menus. Arrange the menus so that one follows the other immediately.

![Image](https://user-images.githubusercontent.com/875194/216178554-7de4ec17-0bde-46e0-b3b1-c1b7f8e7e468.png)

**Comment by clstaudt** [comment]
@flamesjames   Good first issue?

**Comment by flamesjames** [comment]
> @flamesjames Good first issue?

@clstaudt - yes thank you, assigned myself. Do you have a preference of whether you'd like me to work on this or https://github.com/tuttle-dev/tuttle/issues/14 first?

**Comment by clstaudt** [comment]
@flamesjames  No, take your pick. Both are good starting points.

**Comment by flamesjames** [comment]
@clstaudt - do you mind helping point me in the right direction of where I should be looking? I am currently checking `app/home/view.py` but having trouble determining what object the navigation control is. I see where it's being created in `MainMenuItemsHandler` class..

**Comment by clstaudt** [comment]
@vlad-ed-git  It might help you to know that the menus are of type (`views.TNavigationMenu`).

**Comment by flamesjames** [comment]
@clstaudt - the class helps a lot, thanks Christian. I will take a look in free time on it. Much appreciated, will reach out if taking too much time and stuck.

**Comment by flamesjames** [comment]
@clstaudt - apologies.. I'm having a lot of trouble determining how to solve this issue.. you can unassign me and give to someone else.. I'm not sure on the correct approach.

**Comment by clstaudt** [comment]
@flamesjames  Sure, no problem. Regarding your difficulties, what were they? Do you feel you lack some basic knowledge (Python, flet/Flutter, ...) or is it something we could fix (better design, documentation, ...)?

**Comment by flamesjames** [comment]
@clstaudt - I feel it's probably a combination of multiple points you listed.. new to Python and Open Source, not familiar with flet/flutter, and was tough to determine where I had to manipulate to solve the issue so not sure if better documentation would help..

**Comment by vlad-ed-git** [comment]
@clstaudt @flamesjames fixed in #223
