### ISSUE TITLE
pluggy and/or mypy did not work 

### ISSUE THREAD

**Issue by MMdeCastro** [tuttle-dev/tuttle#49]
Following the README.md, I run: `python setup.py develop` and got `error: pluggy 1.0.0 is installed but pluggy<1,>=0.12.0 is required by {'tox'}`. I run the `pytest` anyway and I got:

`ImportError while loading conftest '/home/mmc/my_tools/tuttle/tests/conftest.py'.`
`tests/conftest.py:7: in <module>`
`    import tuttle`
`tuttle/__init__.py:6: in <module>`
`    from . import (`
`tuttle/calendar.py:11: in <module>`
`    from pandera.typing import DataFrame`
`../../../miniconda3/lib/python3.9/site-packages/pandera-0.9.0-py3.9.egg/pandera/__init__.py:31: in <module>`
`    from pandera.engines.numpy_engine import Object`
`../../../miniconda3/lib/python3.9/site-packages/pandera-0.9.0-py3.9.egg/pandera/engines/numpy_engine.py:16: in <module>`
`    from . import engine, utils`
`../../../miniconda3/lib/python3.9/site-packages/pandera-0.9.0-py3.9.egg/pandera/engines/engine.py:22: in <module>`
`    import typing_inspect`
`../../../miniconda3/lib/python3.9/site-packages/typing_inspect-0.7.1-py3.9.egg/typing_inspect.py:13: in <module>`
`    from mypy_extensions import _TypedDictMeta as _TypedDictMeta_Mypy`
`E   ModuleNotFoundError: No module named 'mypy_extensions'`

I'm in Python 3.9.7 on Ubuntu 20.4. Not sure how to proceed, tons of thanks!

**Comment by clstaudt** [comment]
@MMdeCastro  Thanks for testing this. I have updated the requirements in order to fix this.
