### ISSUE TITLE
Layout: App scaffold

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#64]

**Comment by clstaudt** [comment]
@vlad-ed-git  Can we get a footer? Not sure which elements to put there yet but it's good to have it as a option.



![Image](https://user-images.githubusercontent.com/875194/202851541-d65027af-22bd-415d-8e2d-457952c99dfb.png)

**Comment by vlad-ed-git** [comment]
Okay, we can add that to the backlog.

**Comment by clstaudt** [comment]
If it's complicated please add it to the backlog. If it's as easy as it looks here, please add it directly so we can consider the scaffold done. 

https://github.com/flet-dev/flet/discussions/300

**Comment by vlad-ed-git** [comment]
Okay, I will add a footer with copyright text for now.

**Comment by clstaudt** [comment]
Regarding the app scaffold, I think it's a good approach but I am missing two things:
- a footer
-  when scaling the window up, the content container does not fill the entire window

![Image](https://user-images.githubusercontent.com/875194/204135882-d0745280-c95e-4956-bc1f-79b84b55aabe.png)

**Comment by vlad-ed-git** [comment]
Noted.
I am working on a placeholder footer right now.
I will adjust the window height as well, I currently have a small size set
because I was testing scrollability .

**Comment by clstaudt** [comment]
Is it possible to make the footer span the entire window, not just the content area on the right?

**Comment by vlad-ed-git** [comment]
yes absolutely. I will make so.

**Comment by clstaudt** [comment]
![Image](https://user-images.githubusercontent.com/875194/205647135-efb155c1-5801-4dc9-a29b-70cee678def9.png)




@vlad-ed-git 

I found a few issues with the app scaffold:

- If you increase the window size, there is an unused gap between the content are and the footer.
- The entire window content is scrollable, i.e. a scrollbar appears and it tries to scroll. Can we make it "unscrollable"?
- On the other hand, if you go to the contracts screen and try to scroll somewhere in the middle of the content, it does not work. You can only scroll through the contracts if you place the cursor in the top part of the content area, near the headline. That I would consider a bug.
- In the navigation sidebar, the two menus have a lot of space in between them. One menu should immediately follow the other.

**Comment by vlad-ed-git** [comment]
Okay, sorting this asap.

**Comment by clstaudt** [comment]
@vlad-ed-git  Thanks for fixing, the app scaffold is ready to go
