### ISSUE TITLE
Alert: Display Exception

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#65]

**Comment by clstaudt** [comment]
How can I test this?

**Comment by vlad-ed-git** [comment]
Okay, so for this, I have a mechanism to display pop ups as well as
snackbars. So far I have used pop ups for quick and simple forms, and the
snackbar for displaying info (including errors).
I can quickly implement the UI for deleting a project, and show an alert
for confirming that action. But basically the controls for both alerts and
snackbars are implemented.

**Comment by vlad-ed-git** [comment]
**I show example usage when you try to mark a project as complete (in the project details screen).

**Comment by clstaudt** [comment]
Tested, looks good to me.
