### ISSUE TITLE
Notifications: via SnackBar

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#66]

**Comment by clstaudt** [comment]
This is working fine, and I like the implementation as a function. Please remember to add a docstring.

![Image](https://user-images.githubusercontent.com/875194/204136124-52a025a1-82d4-4105-b63f-637016ed940a.png)

**Comment by vlad-ed-git** [comment]
*noted

**Comment by vlad-ed-git** [comment]
docstring added
