### ISSUE TITLE
Navigation: Sidebar

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#67]

**Comment by clstaudt** [comment]
@vlad-ed-git  Can we get a sidebar 
- with icon+text menu items? 
- with grouped items?

Think macOS!

![Image](https://user-images.githubusercontent.com/875194/202851294-7ee7d966-f9e1-4f8d-9dfe-bb5455085253.png)

**Comment by clstaudt** [comment]
Not fixed yet, but I imagine there should be different groups for
1. menu items for viewing and editing data, e.g. contracts
2. menu items for performing workflows, e.g. invoicing 

The current task would be to find out how grouping can be implemented with flet.

**Comment by vlad-ed-git** [comment]
The implementation is basically just *n* navigation rails (we currently use
1), with leading text, put on top of each other in a column.
I will make the adjustment now.
*If you have other design specs on the rest of the features, let me know
please before I implement them differently.

**Comment by clstaudt** [comment]
Can you add two groups / navigation rails  just to demo this way of implementing?

**Comment by vlad-ed-git** [comment]
okay. Will do this.

**Comment by clstaudt** [comment]
The sidebar works fine. I would like to tweak the font and spacing a bit to make it look more macOS like.   

But I am wondering, do we already have more than one menu item group here as discussed?

![Image](https://user-images.githubusercontent.com/875194/204136019-6ef697fb-e6e1-4492-b362-ef2b8ce589a4.png)

**Comment by vlad-ed-git** [comment]
I am adding a sub menu with items such as invoices.
The app's font is the standard font used in iOS devices, perhaps the sizing
is what needs re adjustment. You did mention it's too small in another
comment, I will tweak that a little.

**Comment by vlad-ed-git** [comment]
placeholder sub menu group is added.
font tweaking is done on another issue, thus I am closing this one.
