### ISSUE TITLE
View: Client

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#70]

**Comment by clstaudt** [comment]
It's a bit hard to tell whether the view is finished without meaningful info to display. The ids are database internals and should not be displayed.  What can we do to make a more realistic demo?

![Image](https://user-images.githubusercontent.com/875194/204137813-2e66f889-da4c-406a-8bbb-a32d5483c6b1.png)

**Comment by vlad-ed-git** [comment]
Perhaps we can display the full contact info of the invoicing contact.

**Comment by clstaudt** [comment]
Perhaps a way to jump to all the projects for this client?

**Comment by vlad-ed-git** [comment]
Okay
