### ISSUE TITLE
View: Project

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#71]

**Comment by clstaudt** [comment]
@vlad-ed-git  Is there a reason you duplicated the data model class `Project` in  `projects_model.py`? I would say you can work with the classes in `tuttle.model` - they behave like dataclasses and you can instantiate them without a database connection.

**Comment by vlad-ed-git** [comment]
I am using separate models as placeholders because the current structure in
Tuttle doesn't have the MVI approach under consideration.
The placeholders are light weight with only what's necessary to simulate a
backend, when you start working on the integration you can remove them and
use your actual models.

**Comment by clstaudt** [comment]
hypothesis:  these mock model classes are redundant because you could use the real model classes with the same ease, adding them only creates extra work for removing them later

**Comment by vlad-ed-git** [comment]
The models and the backend will need re writing / re factoring.
As we agreed, the entire project structure is changing (to what you see in
Tuttle UI
basically:
organized by features
With each feature having
    - data source (with models), view, intent, abstractions
) .
Currently it is faster for me to develop the UI with mocks, without
tinkering with anything on the pre existing work. When you are ready to
start integration, I will replace all the mocks with abstractions for you
to implement (actually the abstractions are already written, so it will be
just a matter of deleting mock implementations).
At that point you can reuse the parts you already wrote with some
refactoring and write new parts, as you see fit.

**Comment by clstaudt** [comment]
Looks good to me. Can you maybe move the hashtag next to the project title and display it in a large font and a different text color than the title (e.g. title black, hashtag dark gray)?

![Image](https://user-images.githubusercontent.com/875194/204138794-50202a04-9a20-42ab-8787-84e430e3e902.png)

**Comment by vlad-ed-git** [comment]
Okay, noted.

**Comment by vlad-ed-git** [comment]
removed id from the display.

placing the hashtag component next to the title does not look good when the title is long (as it will be in some cases). I have adjusted the hashtag in its current place. *also this will probably be a clickable element in the future, as a way to filter projects with similar tags.
