### ISSUE TITLE
Dialog: User onboarding

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#72]

**Comment by clstaudt** [comment]
@vlad-ed-git  is this already testable?

**Comment by vlad-ed-git** [comment]
Yes, you can test it.
The tuttle_ui subfolder is a flet project in itself, later when we
integrate, we will make this the main project source.
Currently you can just run by going into this subfolder, and running flet
main.py -d

**Comment by clstaudt** [comment]
I saw this and it's running, but I can't find the user onboarding screen.

**Comment by vlad-ed-git** [comment]
Okay, let me look into this. It should be the first screen you see.

**Comment by clstaudt** [comment]
This is the first screen I see:

![Image](https://user-images.githubusercontent.com/875194/202858768-656a12fe-063b-4db0-905f-8b2585001de4.png)

**Comment by vlad-ed-git** [comment]
oh I see. I by-pass the splash screen during development so I can focus on
the current step without having to login each time it hot reloads.
You can test on your end now by going to:
auth/view/splash_screen.py
- line 64 (self.on_logged_in()) should be removed
- and line 65 un commented.self.check_auth_status()

**Comment by clstaudt** [comment]
How can I test this @vlad-ed-git ?

**Comment by vlad-ed-git** [comment]
I have uncommented the skip login code, the login view should be visible now.
