### ISSUE TITLE
View: Preferences

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#75]

**Comment by clstaudt** [comment]
This is a good start. 
- on my screen the font in the dropdown field is a bit too small - can you show me how to adjust that?

![Image](https://user-images.githubusercontent.com/875194/204136671-f74849d1-b036-4fce-975b-7c7bb872fd1c.png)

**Comment by vlad-ed-git** [comment]
The core.views.selectors defines the drop-down , there is a parameter to
change the font size ...but I am adjusting the font size throughout, so
that should fix it.

**Comment by vlad-ed-git** [comment]
closing, as adjusting font size is under a separate issue.
