### ISSUE TITLE
View: Contract creation

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#82]

**Comment by clstaudt** [comment]
Like the UI in general.
- I get an error message in the snackbar when trying to save the contract
- feature request for next phase: several of the fields should have options to select from dropdown values (e.g. currency, VAT rate,...) and defaults that can be edited in the preferences

![Image](https://user-images.githubusercontent.com/875194/204138227-0e56668b-2437-4382-bbb3-867e2c1583aa.png)

**Comment by vlad-ed-git** [comment]
Yes, the error is just a placeholder to show how the snackbar looks when
there is an error message.

**Comment by vlad-ed-git** [comment]
I removed the placeholder.
