### ISSUE TITLE
Dialog : Edit contact

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#83]

**Comment by clstaudt** [comment]
Nice implementation. 

Font for the form fields is a bit too small.

![Image](https://user-images.githubusercontent.com/875194/204139054-c1c317cd-48f1-460a-8fbc-bd80e16525c8.png)

**Comment by vlad-ed-git** [comment]
*working on overall app font sizing as a separate issue, so closing this issue.
