### ISSUE TITLE
View: Update project

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#86]

**Comment by clstaudt** [comment]
You're on the right track here. But I am getting a "page not found" when trying to edit a project and returning to the main screen. 


![Image](https://user-images.githubusercontent.com/875194/204138897-2ebf4a9f-c3cb-4dc4-b6ee-f960b7a6924c.png)

**Comment by vlad-ed-git** [comment]
Yes, I just noticed this bug earlier too. Working on it.

**Comment by clstaudt** [comment]
fixed
