### ISSUE TITLE
Dialog: Create contact

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#87]

**Comment by clstaudt** [comment]
I like the UI/UX for that. Perhaps the "add new" button could stand out a bit more or be more distinct from the notifications button etc.

![Image](https://user-images.githubusercontent.com/875194/204136546-bb0570a6-9fe1-43c5-a42a-f625f0cef802.png)

**Comment by vlad-ed-git** [comment]
Okay. I am adjusting that.

**Comment by vlad-ed-git** [comment]
"add new" button adjusted
